### PR TITLE
Rewrite loggy

### LINKED ISSUE #8: Configuration cannot be changed once you log once
If you call the logger before setting the `logger.notifications` property, then any subsequent changes to the `logger.notifications` property will be ignored.

I found this bug [when Brunch is called with deprecated options](https://github.com/brunch/brunch). It calls `logger.warn` before loading the configuration, and thus kills the ability to configure the logger.

Instead of just removing the optimization, you could expose a `reloadConfig()` method that invalidates the config and forces the lazy config initialization to run again on the next logging call. You could also solve it by making `.notifications` a method and put the initialization code in there instead of in the `_notify` method, i.e. `logger.config(['warn', 'info', 'error'])`.

Example:

```
var logger = require('./');

logger.error('Configure me after this!');
logger.notifications = ['error', 'warn', 'info'];
logger.info("You should see this, but you don\'t");
```

### LINKED ISSUE #12: ANSI colour not suppressed on non-terminal output
It's polite to suppress colour on `console.log` if `!process.stdout.isTTY`, on `console.error` if `!process.stderr.isTTY`, and on both if `process.env.TERM === 'dumb'`. Otherwise, we end up with log files full of escape sequences.

### PR DESCRIPTION
**Pull request by shvaikalesh**
Closes #12. `chalk` now handles colors, issues should be reported there.
Closes #8. Odd micro-optimizations are removed, params may be updated during runtime.
Closes https://github.com/brunch/brunch/issues/1603. We use different notifier now.

Removes https://github.com/paulmillr/loggy/commit/a993af0ac231d323f9acc4b353b73919e3460cf5 dirty hack because:
1. it should be handled in notifiers
1. we use different one now (Growl is old and not out-of-box, `node-growl` is not very maintained)

Removes https://github.com/paulmillr/loggy/commit/a017430ea1cf93aef548473499852af90c3636fb (copy-pasted sources of old version of `chalk`) because we use it as dependency now. Terminals are constantly evolving (especially Windows 10), community support is a must for supporting colors.

* formats dates with `Intl` API (instead of regexps).
* `log` is now cyan (hope you don't mind; reads nice).
* added `eslint-config-brunch`, `editorconfig`, improved tests and docs.

Mind adding me as collab?

### CODE REVIEW

**Comment by paulmillr** [comment]
1. Let's remove month and date. Let's add it conditionally, only when a day had passed since the loggy inception. So, if you've launched the app at Jan 18 23:50, let's hide the date until 00:00 has passed.
2. `node-notifier` addition increases the package size from `0.03Mb` to `2.63Mb`. Let's roll it back and its changes. I think it's unacceptable for a 50LOC `notifier` to consume 2MB and use *jade*. Let's roll back all changes related to it.

**Comment by shvaikalesh** [comment]
1. That's is a nice feature, will do.
2. Oops, did not checked that. No jade there, but `vendor/` is pretty huge. However, replacing `node-growl` was primary reason for the PR: it is not maintained and does not escape messages properly (brunch/brunch#1603). Also, it requires `Growl` or `terminal-notifier` installed separately to emit notifications, which are both not light dependencies. I've never seen notifications from Brunch before this change.

We can emit macOS notifications with OSA: couple lines of code, no deps. And figure out what to do with other OSes later. WDYT?

**Comment by paulmillr** [comment]
OSA is good, it would handle mac great without `terminal-notifier`. I suggest we keep `growl` for other systems and backwards-compat.

**Comment by lydell** [comment]
@shvaikalesh This might be out-of-scope, but have you thought about if brunch/brunch#1604 requires changes in loggy? Might want to keep that in mind while rewriting here :)

**Comment by shvaikalesh** [comment]
@lydell brunch/brunch#1604 seems like good improvement for me. However, it requires watcher & `FileList` & files re-written so they use utilize promises better.

**Pull request merged**
